# Generated by Django 2.2.1 on 2019-05-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
