# Generated by Django 2.2.1 on 2019-05-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
