# Generated by Django 2.2.1 on 2019-05-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0005_auto_20190519_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator_choice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_choice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
