# Generated by Django 2.2.1 on 2019-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0006_auto_20190519_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
