# Generated by Django 2.2.1 on 2019-05-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0008_auto_20190521_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='competed',
            new_name='completed',
        ),
    ]
