# Generated by Django 2.2.1 on 2019-05-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
