# Generated by Django 2.2.1 on 2019-05-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0012_profile_loses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amount',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='loses',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
